# Generated by Django 3.1.7 on 2021-05-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derivatives', '0004_auto_20210519_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload2',
            name='wl_range_end',
            field=models.IntegerField(default=700),
        ),
        migrations.AlterField(
            model_name='fileupload2',
            name='wl_range_start',
            field=models.IntegerField(default=300),
        ),
    ]
