# Generated by Django 3.1.7 on 2021-04-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fileupload2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload2',
            name='polyorder',
            field=models.IntegerField(choices=[(2, '2'), (4, '4')], default=0),
        ),
    ]
