# Generated by Django 3.1.7 on 2021-05-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='wl_range_end',
            field=models.IntegerField(default=900),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='wl_range_start',
            field=models.IntegerField(default=190),
        ),
    ]
