# Generated by Django 3.1.7 on 2021-05-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derivatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='')),
                ('n_differential', models.IntegerField()),
                ('polyorder', models.IntegerField(choices=[(2, '2'), (4, '4')], default=0)),
                ('window_length', models.IntegerField()),
                ('n_smooth', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
