# Generated by Django 3.1.7 on 2021-05-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derivatives', '0002_auto_20210507_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload2',
            name='wl_range_start',
            field=models.IntegerField(null=True),
        ),
    ]
