# Generated by Django 3.1.7 on 2021-06-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('derivatives', '0005_auto_20210519_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload2',
            name='wl_range_end',
        ),
        migrations.RemoveField(
            model_name='fileupload2',
            name='wl_range_start',
        ),
    ]
