# Generated by Django 3.1.7 on 2021-06-17 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('derivatives', '0006_auto_20210606_0017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUpload2',
            new_name='FileUpload',
        ),
    ]
